n_trajectories_per_scene: 50
allow_stairs: false
set_start_rot_toward_goal: false
min_dist_between_waypoints: 4.0
max_dist_between_waypoints: 8.0
dist_to_goal_threshold: 0.36
robot_radius: 0.18
robot_height: 1.0
move_amount: 0.25
rotate_amount: 30.0
dt: 0.25
margin_to_obst: 0.1
sim_settings: {color_sensor: true, depth_sensor: true, default_agent: 0, height: 256, width: 256, sensor_height: 0.6}
scene_dir: data/scene_datasets/hm3d/train/
scene_ids:
  - 00005-yPKGKBCyYx8/yPKGKBCyYx8.basis.glb
  - 00006-HkseAnWCgqk/HkseAnWCgqk.basis.glb
  - 00007-UQuchpekHRJ/UQuchpekHRJ.basis.glb
  - 00008-VYnUX657cVo/VYnUX657cVo.basis.glb
  - 00009-vLpv2VX547B/vLpv2VX547B.basis.glb
scene_dataset_config_files:
  - hm3d_annotated_train_basis.scene_dataset_config.json
  - hm3d_annotated_train_basis.scene_dataset_config.json
  - hm3d_annotated_train_basis.scene_dataset_config.json
  - hm3d_annotated_train_basis.scene_dataset_config.json
  - hm3d_annotated_train_basis.scene_dataset_config.json
