n_trajectories_per_scene: 100
allow_stairs: false
set_start_rot_toward_goal: false
min_dist_between_waypoints: 4.0
max_dist_between_waypoints: 8.0
dist_to_goal_threshold: 0.36
robot_radius: 0.18
robot_height: 1.0
move_amount: 0.25
rotate_amount: 30.0
dt: 0.25
margin_to_obst: 0.1
sim_settings:
  color_sensor: true
  depth_sensor: true
  default_agent: 0
  height: 256
  width: 256
  sensor_height: 0.6
scene_dir: data/scene_datasets/hm3d/train/
scene_ids:
- 00000-kfPV7w3FaU5/kfPV7w3FaU5.basis.glb
- 00001-UVdNNRcVyV1/UVdNNRcVyV1.basis.glb
- 00002-FxCkHAfgh7A/FxCkHAfgh7A.basis.glb
- 00003-NtVbfPCkBFy/NtVbfPCkBFy.basis.glb
- 00004-VqCaAuuoeWk/VqCaAuuoeWk.basis.glb
- 00005-yPKGKBCyYx8/yPKGKBCyYx8.basis.glb
- 00006-HkseAnWCgqk/HkseAnWCgqk.basis.glb
- 00007-UQuchpekHRJ/UQuchpekHRJ.basis.glb
- 00008-VYnUX657cVo/VYnUX657cVo.basis.glb
- 00009-vLpv2VX547B/vLpv2VX547B.basis.glb
- 00010-DBjEcHFg4oq/DBjEcHFg4oq.basis.glb
- 00011-1W61QJVDBqe/1W61QJVDBqe.basis.glb
- 00012-kDgLKdMd5X8/kDgLKdMd5X8.basis.glb
- 00013-sfbj7jspYWj/sfbj7jspYWj.basis.glb
- 00014-nYYcLpSzihC/nYYcLpSzihC.basis.glb
- 00015-LPwS1aEGXBb/LPwS1aEGXBb.basis.glb
- 00016-qk9eeNeR4vw/qk9eeNeR4vw.basis.glb
- 00017-oEPjPNSPmzL/oEPjPNSPmzL.basis.glb
- 00018-as8Y8AYx6yW/as8Y8AYx6yW.basis.glb
- 00019-AfKhsVmG8L4/AfKhsVmG8L4.basis.glb
- 00020-XYyR54sxe6b/XYyR54sxe6b.basis.glb
- 00021-yQESfVcg18k/yQESfVcg18k.basis.glb
- 00022-gmuS7Wgsbrx/gmuS7Wgsbrx.basis.glb
- 00023-zepmXAdrpjR/zepmXAdrpjR.basis.glb
- 00024-XNoaAZwsWKk/XNoaAZwsWKk.basis.glb
- 00025-ixTj1aTMup2/ixTj1aTMup2.basis.glb
- 00026-tzaZQQmUVXZ/tzaZQQmUVXZ.basis.glb
- 00027-cVppJowrUqs/cVppJowrUqs.basis.glb
- 00028-xGnehmjiCSA/xGnehmjiCSA.basis.glb
- 00029-4wCTuaUNWEd/4wCTuaUNWEd.basis.glb
- 00030-LPEMkRVudUm/LPEMkRVudUm.basis.glb
- 00031-Wo6kuutE9i7/Wo6kuutE9i7.basis.glb
- 00032-jTTGECZYKRA/jTTGECZYKRA.basis.glb
- 00033-oPj9qMxrDEa/oPj9qMxrDEa.basis.glb
- 00034-6imZUJGRUq4/6imZUJGRUq4.basis.glb
- 00035-3XYAD64HpDr/3XYAD64HpDr.basis.glb
- 00036-41FNXLAZZgC/41FNXLAZZgC.basis.glb
- 00037-oKFJo8jpzRW/oKFJo8jpzRW.basis.glb
- 00038-aJg466zMSNt/aJg466zMSNt.basis.glb
- 00039-ANmWrL7Kz7h/ANmWrL7Kz7h.basis.glb
- 00040-ZB8o8rMmPdB/ZB8o8rMmPdB.basis.glb
- 00041-QKfBMSSy7Hy/QKfBMSSy7Hy.basis.glb
- 00042-qDjhFcNqFPi/qDjhFcNqFPi.basis.glb
- 00043-Jfyvj3xn2aJ/Jfyvj3xn2aJ.basis.glb
- 00044-kuxpR2xHUBa/kuxpR2xHUBa.basis.glb
- 00045-mt5PhMmTk5m/mt5PhMmTk5m.basis.glb
- 00046-UQ5EhY5wve1/UQ5EhY5wve1.basis.glb
- 00047-u9LiqMn6kA6/u9LiqMn6kA6.basis.glb
- 00048-aKwZ7VJDAjr/aKwZ7VJDAjr.basis.glb
- 00049-e3YKRHQRPNe/e3YKRHQRPNe.basis.glb
- 00050-wrq3kiEU4VR/wrq3kiEU4VR.basis.glb
- 00051-CETmJJqkhcK/CETmJJqkhcK.basis.glb
- 00052-H1D2FZ8TAv1/H1D2FZ8TAv1.basis.glb
- 00053-kAMF2R7PCqX/kAMF2R7PCqX.basis.glb
- 00054-6BReaxZUoMg/6BReaxZUoMg.basis.glb
- 00055-HxmXPBbFCkH/HxmXPBbFCkH.basis.glb
- 00056-kdw2Uapns3b/kdw2Uapns3b.basis.glb
- 00057-1UnKg1rAb8A/1UnKg1rAb8A.basis.glb
- 00058-1hovphK64XQ/1hovphK64XQ.basis.glb
- 00059-kJxT5qssH4H/kJxT5qssH4H.basis.glb
- 00060-TgWKHxhJAng/TgWKHxhJAng.basis.glb
- 00061-duthTPisf28/duthTPisf28.basis.glb
- 00062-ACZZiU6BXLz/ACZZiU6BXLz.basis.glb
- 00063-KsD3yx9nZCv/KsD3yx9nZCv.basis.glb
- 00064-gQgtJ9Stk5s/gQgtJ9Stk5s.basis.glb
- 00065-kZhZfAhdnNN/kZhZfAhdnNN.basis.glb
- 00066-nHHVbEyHX3t/nHHVbEyHX3t.basis.glb
- 00067-osQy15y8EVT/osQy15y8EVT.basis.glb
- 00068-812QqCky3T7/812QqCky3T7.basis.glb
- 00069-Y8Y6ukxGMvn/Y8Y6ukxGMvn.basis.glb
- 00070-w7QyjJ3H9Bp/w7QyjJ3H9Bp.basis.glb
- 00071-GCEb4nmNi7j/GCEb4nmNi7j.basis.glb
- 00072-t8wCA6Qe8uT/t8wCA6Qe8uT.basis.glb
- 00073-bCFcvb4zc3N/bCFcvb4zc3N.basis.glb
- 00074-kHvNo8x6Qoe/kHvNo8x6Qoe.basis.glb
- 00075-u3zrj4Nojev/u3zrj4Nojev.basis.glb
- 00076-fJ1GEE6PdHD/fJ1GEE6PdHD.basis.glb
- 00077-z9VLaZqCsW5/z9VLaZqCsW5.basis.glb
- 00078-nJTPfwbAj4S/nJTPfwbAj4S.basis.glb
- 00079-2ihrkjrbHVf/2ihrkjrbHVf.basis.glb
- 00080-gPf8XzHACGn/gPf8XzHACGn.basis.glb
- 00081-5biL7VEkByM/5biL7VEkByM.basis.glb
- 00082-y4YiUQwvWGH/y4YiUQwvWGH.basis.glb
- 00083-16tymPtM7uS/16tymPtM7uS.basis.glb
- 00084-CtZLhCbWFm7/CtZLhCbWFm7.basis.glb
- 00085-KWoYKrff5L4/KWoYKrff5L4.basis.glb
- 00086-315QujoX279/315QujoX279.basis.glb
- 00087-YY8rqV6L6rf/YY8rqV6L6rf.basis.glb
- 00088-z9w4aD7JsiQ/z9w4aD7JsiQ.basis.glb
- 00089-Am8wmPcBmtN/Am8wmPcBmtN.basis.glb
- 00090-C8VQQtzUoqV/C8VQQtzUoqV.basis.glb
- 00091-SA759ShSs44/SA759ShSs44.basis.glb
- 00092-1mCzDx3EMom/1mCzDx3EMom.basis.glb
- 00093-HneuS3CYDFG/HneuS3CYDFG.basis.glb
- 00094-WT4QWwXrMzs/WT4QWwXrMzs.basis.glb
- 00095-HsYeeztxPG6/HsYeeztxPG6.basis.glb
- 00096-6HRFAUDqpTb/6HRFAUDqpTb.basis.glb
- 00097-rPwrKEnR3fk/rPwrKEnR3fk.basis.glb
- 00098-MVStfLiYYQv/MVStfLiYYQv.basis.glb
- 00099-226REUyJh2K/226REUyJh2K.basis.glb
scene_dataset_config_files:
- hm3d_annotated_train_basis.scene_dataset_config.json
- hm3d_annotated_train_basis.scene_dataset_config.json
- hm3d_annotated_train_basis.scene_dataset_config.json
- hm3d_annotated_train_basis.scene_dataset_config.json
- hm3d_annotated_train_basis.scene_dataset_config.json
- hm3d_annotated_train_basis.scene_dataset_config.json
- hm3d_annotated_train_basis.scene_dataset_config.json
- hm3d_annotated_train_basis.scene_dataset_config.json
- hm3d_annotated_train_basis.scene_dataset_config.json
- hm3d_annotated_train_basis.scene_dataset_config.json
- hm3d_annotated_train_basis.scene_dataset_config.json
- hm3d_annotated_train_basis.scene_dataset_config.json
- hm3d_annotated_train_basis.scene_dataset_config.json
- hm3d_annotated_train_basis.scene_dataset_config.json
- hm3d_annotated_train_basis.scene_dataset_config.json
- hm3d_annotated_train_basis.scene_dataset_config.json
- hm3d_annotated_train_basis.scene_dataset_config.json
- hm3d_annotated_train_basis.scene_dataset_config.json
- hm3d_annotated_train_basis.scene_dataset_config.json
- hm3d_annotated_train_basis.scene_dataset_config.json
- hm3d_annotated_train_basis.scene_dataset_config.json
- hm3d_annotated_train_basis.scene_dataset_config.json
- hm3d_annotated_train_basis.scene_dataset_config.json
- hm3d_annotated_train_basis.scene_dataset_config.json
- hm3d_annotated_train_basis.scene_dataset_config.json
- hm3d_annotated_train_basis.scene_dataset_config.json
- hm3d_annotated_train_basis.scene_dataset_config.json
- hm3d_annotated_train_basis.scene_dataset_config.json
- hm3d_annotated_train_basis.scene_dataset_config.json
- hm3d_annotated_train_basis.scene_dataset_config.json
- hm3d_annotated_train_basis.scene_dataset_config.json
- hm3d_annotated_train_basis.scene_dataset_config.json
- hm3d_annotated_train_basis.scene_dataset_config.json
- hm3d_annotated_train_basis.scene_dataset_config.json
- hm3d_annotated_train_basis.scene_dataset_config.json
- hm3d_annotated_train_basis.scene_dataset_config.json
- hm3d_annotated_train_basis.scene_dataset_config.json
- hm3d_annotated_train_basis.scene_dataset_config.json
- hm3d_annotated_train_basis.scene_dataset_config.json
- hm3d_annotated_train_basis.scene_dataset_config.json
- hm3d_annotated_train_basis.scene_dataset_config.json
- hm3d_annotated_train_basis.scene_dataset_config.json
- hm3d_annotated_train_basis.scene_dataset_config.json
- hm3d_annotated_train_basis.scene_dataset_config.json
- hm3d_annotated_train_basis.scene_dataset_config.json
- hm3d_annotated_train_basis.scene_dataset_config.json
- hm3d_annotated_train_basis.scene_dataset_config.json
- hm3d_annotated_train_basis.scene_dataset_config.json
- hm3d_annotated_train_basis.scene_dataset_config.json
- hm3d_annotated_train_basis.scene_dataset_config.json
- hm3d_annotated_train_basis.scene_dataset_config.json
- hm3d_annotated_train_basis.scene_dataset_config.json
- hm3d_annotated_train_basis.scene_dataset_config.json
- hm3d_annotated_train_basis.scene_dataset_config.json
- hm3d_annotated_train_basis.scene_dataset_config.json
- hm3d_annotated_train_basis.scene_dataset_config.json
- hm3d_annotated_train_basis.scene_dataset_config.json
- hm3d_annotated_train_basis.scene_dataset_config.json
- hm3d_annotated_train_basis.scene_dataset_config.json
- hm3d_annotated_train_basis.scene_dataset_config.json
- hm3d_annotated_train_basis.scene_dataset_config.json
- hm3d_annotated_train_basis.scene_dataset_config.json
- hm3d_annotated_train_basis.scene_dataset_config.json
- hm3d_annotated_train_basis.scene_dataset_config.json
- hm3d_annotated_train_basis.scene_dataset_config.json
- hm3d_annotated_train_basis.scene_dataset_config.json
- hm3d_annotated_train_basis.scene_dataset_config.json
- hm3d_annotated_train_basis.scene_dataset_config.json
- hm3d_annotated_train_basis.scene_dataset_config.json
- hm3d_annotated_train_basis.scene_dataset_config.json
- hm3d_annotated_train_basis.scene_dataset_config.json
- hm3d_annotated_train_basis.scene_dataset_config.json
- hm3d_annotated_train_basis.scene_dataset_config.json
- hm3d_annotated_train_basis.scene_dataset_config.json
- hm3d_annotated_train_basis.scene_dataset_config.json
- hm3d_annotated_train_basis.scene_dataset_config.json
- hm3d_annotated_train_basis.scene_dataset_config.json
- hm3d_annotated_train_basis.scene_dataset_config.json
- hm3d_annotated_train_basis.scene_dataset_config.json
- hm3d_annotated_train_basis.scene_dataset_config.json
- hm3d_annotated_train_basis.scene_dataset_config.json
- hm3d_annotated_train_basis.scene_dataset_config.json
- hm3d_annotated_train_basis.scene_dataset_config.json
- hm3d_annotated_train_basis.scene_dataset_config.json
- hm3d_annotated_train_basis.scene_dataset_config.json
- hm3d_annotated_train_basis.scene_dataset_config.json
- hm3d_annotated_train_basis.scene_dataset_config.json
- hm3d_annotated_train_basis.scene_dataset_config.json
- hm3d_annotated_train_basis.scene_dataset_config.json
- hm3d_annotated_train_basis.scene_dataset_config.json
- hm3d_annotated_train_basis.scene_dataset_config.json
- hm3d_annotated_train_basis.scene_dataset_config.json
- hm3d_annotated_train_basis.scene_dataset_config.json
- hm3d_annotated_train_basis.scene_dataset_config.json
- hm3d_annotated_train_basis.scene_dataset_config.json
- hm3d_annotated_train_basis.scene_dataset_config.json
- hm3d_annotated_train_basis.scene_dataset_config.json
- hm3d_annotated_train_basis.scene_dataset_config.json
- hm3d_annotated_train_basis.scene_dataset_config.json
- hm3d_annotated_train_basis.scene_dataset_config.json
