allow_stairs: false
randomize_start_rotation: true
randomize_waypoint_rotation: false

max_waypoints_per_episode: 32
max_steps_per_waypoint: 200

min_dist_between_waypoints: 4.0
max_dist_between_waypoints: 8.0
move_amount: 0.25
dist_to_goal_threshold: 0.36
coll_move_diff_threshold: 0.001

margin_to_obst: 0.1
robot_radius: 0.18
robot_height: 1.0

sim_settings:
  color_sensor: true
  default_agent: 0
  height: 256
  width: 256
  sensor_height: 0.6

scene_dir: data/scene_datasets/mp3d_example/
scene_ids: [
  "17DRP5sb8fy",
]
scene_dataset_config_files: [
  "mp3d.scene_dataset_config.json"
]